version: "3.7"
services:
  db:
    image: postgres:11.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: tuan-example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api1:
    build: ./sample1
    container_name: sample-service1
    ports:
        - "3000:3000"
    networks:
        - webnet
    # volumes:
    #  - ./sample1/:/app
    restart: always
    depends_on:
     - db
  api2:
    build: ./sample2
    container_name: sample-service2
    ports:
     - "3100:3100"
    # volumes:
    #  - ./sample2/:/app
    restart: always
    depends_on:
     - db
  nginx:
        build:
            context: ./nginx
            # args:
            #     - WEB_REVERSE_PROXY_PORT=8000
            #     - WEB_SSL=false
            #     - SELF_SIGNED=false
            #     - NO_DEFAULT=false
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true
        networks:
            - webnet
        container_name: nginx-container
        restart: always
        depends_on: 
            - api1
            - api2
networks:
    webnet:
        name: webnet
        driver: bridge